version: '3.8'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres-stock-alert
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stock-alert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: duchuy
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq-stock-alert
    ports:
      - "5672:5672"
      - "15672:15672"

  influxdb:
    image: influxdb:latest
    container_name: influxdb-stock-alert
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: stock-alert
      INFLUXDB_ADMIN_USER: influx
      INFLUXDB_ADMIN_PASSWORD: duchuy1311
    volumes:
      - influxdb-data:/var/lib/influxdb2

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-stock-alert
    links:
      - postgres
      - rabbitmq
      - influxdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stock-alert
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: duchuy
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: bW6eoLcswptcDR1Y8n_-7vyccwdeutBgU7grHtU9Mct8cKCVdv7wqLVLXTdAWQ2iHiW7YNXPp3cl2aheLqf5cw==
      INFLUXDB_ORG: stock-alert
      INFLUXDB_BUCKET: stock-alert
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - influxdb

volumes:
  postgres-data:
  influxdb-data: